---
title: "Análisis datos CuidAME"
author:
  - name: "Alejandro Caravaca Puchades"
    orcid: 0000-0003-2223-7335
    email: "acaravaca@idibell.cat"
    affiliation: "Hospital Universitari de Bellvitge -- IDIBELL"
format:
  html:
    df-print: paged
    embed-resources: true
execute:
  warning: false
---

```{r}
library(dunn.test)
library(ggeffects)
library(ggplot2)
library(ggpubr)
library(gtsummary)
library(sjPlot)
library(tidyverse)
```

```{r}
source("R/data.R")
source("R/lmm_hfmse.R")
source("R/lmm_rulm.R")
```

# Diferencias entre tratamientos

```{r}
pacientes |>
  mutate(
    gender = case_match(gender,
        "M" ~ "Male",
        "F" ~ "Female"
      ) |>
      factor(levels = c("Female", "Male")),
    treatment = case_match(txgroup,
        "NO TREATED" ~ "No treatment",
        "NUS" ~ "Nusinersen",
        "RIS" ~ "Risdiplam"
      ) |>
      factor(levels = c("No treatment", "Nusinersen", "Risdiplam"))
  ) |>
  select(gender, age, sma_type, smn2num, treatment) |>
  tbl_summary(by="treatment") |>
  add_p()
```

```{r}
datos_escalas |>
  mutate(scale = factor(scale, levels = c(
    "HFMSE", "RULM", "ALSFRS_R", "EK2", "WALK_TEST", "CHOP"
  ))) |>
  ggplot(aes(age, score, color=smn2num, group=patient_id)) +
  geom_line() + 
  facet_wrap(~ scale, scales="free")
```

```{r}
datos_escalas |>
  mutate(scale = factor(scale, levels = c(
    "HFMSE", "RULM", "ALSFRS_R", "EK2", "WALK_TEST", "CHOP"
  ))) |>
  ggplot(aes(age, score, color=txgroup, group=patient_id)) +
  geom_line() + 
  facet_wrap(~ scale, scales="free")
```

```{r}
tab_model(hfmse.fit, dv.labels = "HFMSE [/66]")
```

```{r}
ggeffect(hfmse.fit, c("age", "txgroup", "sma_type")) |> plot() +
  scale_x_continuous(limits=c(18, 75), breaks=seq(20, 75, 10)) +
  labs(x = "Age", y = "HFMSE [/66]", color = "Treatment")
```

```{r}
ggeffect(hfmse.fit, c("age", "treatment_start_age", "txgroup")) |> plot() +
  scale_x_continuous(limits=c(18, 75), breaks=seq(20, 75, 10)) +
  labs(x = "Age", y = "HFMSE [/66]", color = "Treatment start")
```

```{r}
tab_model(rulm.fit, dv.labels = "RULM [/37]")
```

```{r}
ggeffect(rulm.fit, c("age", "txgroup", "sma_type")) |> plot() +
  scale_x_continuous(limits=c(18, 75), breaks=seq(20, 75, 10)) +
  labs(x = "Age", y = "RULM [/37]", color = "Treatment")
```

```{r}
ggeffect(rulm.fit, c("age", "treatment_start_age", "txgroup")) |> plot() +
  scale_x_continuous(limits=c(18, 75), breaks=seq(20, 75, 10)) +
  labs(x = "Age", y = "RULM [/37]", color = "Treatment start")
```

# Análisis de coste-efectividad

```{r}
compare_treatments <- function(model, treatment.a, treatment.b, duration_years,
                               treatment_start_age=20, sma_type="SMA-II", gender="M", smn2num="3")
{
  common_traits = data.frame(patient_id="dummy", sma_type=sma_type, gender=gender, smn2num=smn2num,
                             treatment_start_age=treatment_start_age)
  a_start = predict(model, level=0, newdata=cbind(common_traits, data.frame(
    txgroup=treatment.a, age=treatment_start_age, years_from_baseline=0
  )))
  a_end = predict(model, level=0, newdata=cbind(common_traits, data.frame(
    txgroup=treatment.a, age=treatment_start_age+duration_years, years_from_baseline=duration_years
  )))
  
  b_start = predict(model, level=0, newdata=cbind(common_traits, data.frame(
    txgroup=treatment.b, age=treatment_start_age, years_from_baseline=0
  )))
  b_end = predict(model, level=0, newdata=cbind(common_traits, data.frame(
    txgroup=treatment.b, age=treatment_start_age+duration_years, years_from_baseline=duration_years
  )))
  
  return(as.numeric((a_end - a_start) - (b_end - b_start)))
}

calculate_treatment_icer <- function(model, treatment.a, treatment.b, duration_years,
                                     treatment.a.cost.first, treatment.a.cost.after,
                                     treatment.b.cost.first, treatment.b.cost.after)
{
  df <- data.frame(treatment.a=treatment.a, treatment.b=treatment.b) |>
    cross_join(data.frame(t=duration_years)) |>
    mutate(
      cost.a = treatment.a.cost.first + treatment.a.cost.after * (t-1),
      cost.b = treatment.b.cost.first + treatment.b.cost.after * (t-1),
      cost.a_vs_b = cost.a - cost.b,
      efficacy.a_vs_b = compare_treatments(model, treatment.a, treatment.b, t),
      icer.a_vs_b = cost.a_vs_b / efficacy.a_vs_b
    )
  return(df)
}

rulm_icer.nus_vs_ris <- calculate_treatment_icer(
  rulm.fit, treatment.a="NUS", treatment.b="RIS", duration_years=1:10,
  treatment.a.cost.first=420000, treatment.a.cost.after=210000,
  treatment.b.cost.first=251996, treatment.b.cost.after=251996
)

hfmse_icer.nus_vs_ris <- calculate_treatment_icer(
  hfmse.fit, treatment.a="NUS", treatment.b="RIS", duration_years=1:10,
  treatment.a.cost.first=420000, treatment.a.cost.after=210000,
  treatment.b.cost.first=251996, treatment.b.cost.after=251996
)

icer.nus_vs_ris <- bind_rows(
  rulm_icer.nus_vs_ris |> mutate(scale="RULM"),
  hfmse_icer.nus_vs_ris |> mutate(scale="HFMSE")
)
```

```{r}
icer.nus_vs_ris |>
  filter(scale == "RULM") |>
  mutate(cost_interpretation = case_when(
    cost.a_vs_b > 0 ~ str_glue("Favours {treatment.b}"),
    cost.a_vs_b < 0 ~ str_glue("Favours {treatment.a}"),
  ) |> factor(levels=c("Favours RIS", "Favours NUS"))) |>
  ggplot(aes(t, cost.a_vs_b)) +
  geom_col(aes(fill=cost_interpretation)) +
  scale_x_continuous(breaks=seq(2, 10, 2)) +
  scale_y_continuous(labels=scales::dollar_format(prefix="", suffix="€")) +
  labs(
    fill="Cost Analysis",
    x = "Treatment duration (years)", y = "Cost difference: NUS - RIS",
  ) +
  theme(legend.position = "top")
```

```{r}
ggplot(icer.nus_vs_ris, aes(t, icer.a_vs_b)) +
  geom_line() + geom_point() +
  facet_wrap(~scale, ncol=1) +
  scale_x_continuous(breaks=seq(2, 10, 2)) +
  scale_y_continuous(labels=scales::dollar_format(prefix="", suffix="€")) +
  labs(
    title = "Cost Effectiveness Analysis: NUS vs. RIS",
    x = "Treatment duration (years)", y = "ICER"
  )
```

# Diferencias en inicio de tratamiento entre CC.AA.

```{r}
with(pacientes_ccaa, table(ccaa, sma_type))
```

```{r}
with(pacientes_ccaa, table(ccaa, treated))
```

```{r}
fisher.test(with(pacientes_ccaa, table(ccaa, treated)))
```

```{r}
with(pacientes_ccaa, table(ccaa, txgroup, sma_type))
```

```{r}
pacientes_ccaa.sma2 <- filter(pacientes_ccaa, sma_type == "SMA-II")
pacientes_ccaa.sma3 <- filter(pacientes_ccaa, sma_type == "SMA-III")
```

```{r}
pacientes_ccaa |>
  drop_na(sma_type) |>
  ggline(x="ccaa", y="treatment_start_age", color="sma_type", add="mean_se") +
  theme(axis.text.x = element_text(angle=45, hjust=1))
```

```{r}
pacientes_ccaa |>
  drop_na(ccaa, sma_type, birth_d) |>
  ggplot(aes(year(birth_d), ccaa)) +
    geom_boxplot() +
    facet_wrap(~sma_type)
```

```{r}
aov(treatment_start_age ~ ccaa, pacientes_ccaa.sma2) |> plot()
```

```{r}
kruskal.test(treatment_start_age ~ ccaa, pacientes_ccaa.sma2)
```

```{r}
with(pacientes_ccaa.sma2,
     dunn.test(treatment_start_age, ccaa, method = "bonferroni"))
```

```{r}
ggplot(pacientes_ccaa.sma2, aes(ccaa, year(birth_d))) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle=45, hjust=1)) +
  labs(title = "Differences in patient inclusion among different CC.AA.",
       x = "CC.AA.", y = "Birth Year")
```

```{r}
aov(year(birth_d) ~ ccaa, pacientes_ccaa.sma2) |> plot()
```

```{r}
kruskal.test(year(birth_d) ~ ccaa, pacientes_ccaa.sma2)
```

```{r}
with(pacientes_ccaa.sma2,
     dunn.test(year(birth_d), ccaa, method = "bonferroni"))
```

```{r}
aov(treatment_start_age ~ ccaa, data = pacientes_ccaa.sma3) |> plot()
```

```{r}
oneway.test(treatment_start_age ~ ccaa, pacientes_ccaa.sma3)
```